### PR TITLE
Fix errors for mitamae

### PR DESCRIPTION
**Pull request by ta1kt0me**
This plugin doesn't work in mitamae v1.4.1 because of below errors.

- uninitialized constant #<Class:0x7feee680bbc0>::MItamae::Resource (NameError)
- undefined method 'pip' for #<MItamae::RecipeContext:0x7f9e968db3a0> (NoMethodError)
- ArgumentError: 'apply': wrong number of arguments (0 for 2)

### CODE REVIEW

**Comment by katsyoshi** [comment]
thanks!
